export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        teal:         "#1FB29C",
        "teal-dark":  "#17967f",
        "teal-darker":"#0d7a66",
        l1:           "#E3EBF0",
        l2:           "#D5E5ED",
        l3:           "#BFD6DE",
        accent:       "#ADCFE6",
        accent2:      "#BDDBEF",
        ink:          "#0f2d2a",
        ink2:         "#2d5a52",
        mid:          "#5a8a80",
        faint:        "#8ab8b0",
        "green-bg":   "#e6f7f4",
        "green-bdr":  "#a8ddd6",
        "green-dark": "#0d7a66",
        "red-bg":     "#fdeaea",
        "red-bdr":    "#f5b8b8",
        "red-dark":   "#9b2c2c",
        "amber-c":    "#e89a2a",
        "amber-bg":   "#fff4e0",
        "amber-bdr":  "#f5d08a",
        "amber-dark": "#7a4f00",
        "blue-c":     "#3a82c4",
        "blue-bg":    "#e8f1fb",
        "blue-bdr":   "#a8c8f0",
      },
      fontFamily: {
        sans:  ['"DM Sans"', "sans-serif"],
        serif: ['"Fraunces"', "serif"],
      },
    },
  },
  plugins: [],
};
